USE AdventureWorks2019
GO
SELECT * FROM sys.dm_db_index_usage_stats
GO
SELECT * FROM [Person].[PersonPhone]							with (INDEX ([IX_PersonPhone_PhoneNumber]) ) 
SELECT * FROM [Production].[ProductCategory]					with (INDEX (		[AK_ProductCategory_Name] ))
SELECT * FROM [Sales].[CurrencyRate]							with (INDEX ([AK_CurrencyRate_CurrencyRateDate_FromCurrencyCode_ToCurrencyCode]  ))
SELECT * FROM [HumanResources].[Employee]						with (INDEX (	[IX_Employee_OrganizationNode]  ))
SELECT * FROM [Production].[Location]							with (INDEX ([AK_Location_Name]  ))

use WideWorldImporters
GO
SELECT * FROM sys.dm_db_index_usage_stats
GO
SELECT * FROM [Sales].[OrderLines]								with (INDEX ([FK_Sales_OrderLines_OrderID]  ))
SELECT * FROM [Sales].[OrderLines]								with (INDEX ([FK_Sales_OrderLines_PackageTypeID]  ))
SELECT * FROM [Sales].[OrderLines]								with (INDEX (	[IX_Sales_OrderLines_AllocatedStockItems]  ))
SELECT * FROM [Sales].[OrderLines]								with (INDEX (	[IX_Sales_OrderLines_Perf_20160301_01]  ))
SELECT * FROM [Sales].[OrderLines]								with (INDEX (	[IX_Sales_OrderLines_Perf_20160301_02]  ))
SELECT * FROM [Sales].[OrderLines]								with (INDEX (	[NCCX_Sales_OrderLines]  ))
SELECT * FROM [Application].[StateProvinces]					with (INDEX (			[FK_Application_StateProvinces_CountryID]  ))
SELECT * FROM [Application].[StateProvinces]					with (INDEX (			[IX_Application_StateProvinces_SalesTerritory]  ))
SELECT * FROM [Sales].[CustomerTransactions]					with (INDEX (			[FK_Sales_CustomerTransactions_CustomerID]  ))
SELECT * FROM [Sales].[CustomerTransactions]					with (INDEX (			[FK_Sales_CustomerTransactions_TransactionTypeID]  ))
SELECT * FROM [Sales].[CustomerTransactions]					with (INDEX (			[FK_Sales_CustomerTransactions_InvoiceID]  ))
SELECT * FROM [Sales].[CustomerTransactions]					with (INDEX (			[FK_Sales_CustomerTransactions_PaymentMethodID]  ))
SELECT * FROM [Sales].[CustomerTransactions]					with (INDEX (			[IX_Sales_CustomerTransactions_IsFinalized]  ))
SELECT * FROM [Application].[Cities]							with (INDEX (	[FK_Application_Cities_StateProvinceID]  ))
SELECT * FROM [Application].[SystemParameters]					with (INDEX (			[FK_Application_SystemParameters_DeliveryCityID]  ))
SELECT * FROM [Application].[SystemParameters]					with (INDEX (			[FK_Application_SystemParameters_PostalCityID]  ))
SELECT * FROM [Sales].[InvoiceLines]							with (INDEX (	[FK_Sales_InvoiceLines_InvoiceID]  ))
SELECT * FROM [Sales].[InvoiceLines]							with (INDEX (	[FK_Sales_InvoiceLines_StockItemID]  ))

SELECT  * FROM [Sales].[InvoiceLines]							with (INDEX (	[FK_Sales_InvoiceLines_PackageTypeID] ))  
SELECT  * FROM [Sales].[InvoiceLines]							with (INDEX (	[NCCX_Sales_InvoiceLines] ))  
SELECT  * FROM [Purchasing].[Suppliers]							with (INDEX (	[FK_Purchasing_Suppliers_SupplierCategoryID] ))  
SELECT  * FROM [Purchasing].[Suppliers]							with (INDEX (	[FK_Purchasing_Suppliers_PrimaryContactPersonID] ))  
SELECT  * FROM [Purchasing].[Suppliers]							with (INDEX (	[FK_Purchasing_Suppliers_AlternateContactPersonID] ))  
SELECT  * FROM [Purchasing].[Suppliers]							with (INDEX (	[FK_Purchasing_Suppliers_DeliveryMethodID] ))  
SELECT  * FROM [Purchasing].[Suppliers]							with (INDEX (	[FK_Purchasing_Suppliers_DeliveryCityID] ))  
SELECT  * FROM [Purchasing].[Suppliers]							with (INDEX (	[FK_Purchasing_Suppliers_PostalCityID] ))  
SELECT  * FROM [Warehouse].[StockItemTransactions]							with (INDEX (	[FK_Warehouse_StockItemTransactions_StockItemID] ))  
SELECT  * FROM [Warehouse].[StockItemTransactions]							with (INDEX (	[FK_Warehouse_StockItemTransactions_TransactionTypeID] ))  
SELECT  * FROM [Warehouse].[StockItemTransactions]							with (INDEX (	[FK_Warehouse_StockItemTransactions_CustomerID] ))  



SELECT  * FROM [Warehouse].[StockItemTransactions]							with (INDEX (	[FK_Warehouse_StockItemTransactions_InvoiceID] ))  
SELECT  * FROM [Warehouse].[StockItemTransactions]							with (INDEX (	[FK_Warehouse_StockItemTransactions_SupplierID] ))  
SELECT  * FROM [Warehouse].[StockItemTransactions]								with (INDEX (	[FK_Warehouse_StockItemTransactions_PurchaseOrderID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_CustomerCategoryID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_BuyingGroupID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_PrimaryContactPersonID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_AlternateContactPersonID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_DeliveryMethodID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_DeliveryCityID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[FK_Sales_Customers_PostalCityID] ))  
SELECT  * FROM [Sales].[Customers]							with (INDEX (	[IX_Sales_Customers_Perf_20160301_06] ))  
SELECT  * FROM [Purchasing].[PurchaseOrders]							with (INDEX (	[FK_Purchasing_PurchaseOrders_SupplierID] ))  
SELECT  * FROM [Purchasing].[PurchaseOrders]							with (INDEX (	[FK_Purchasing_PurchaseOrders_DeliveryMethodID] ))  
SELECT  * FROM [Purchasing].[PurchaseOrders]							with (INDEX (	[FK_Purchasing_PurchaseOrders_ContactPersonID] ))  
SELECT  * FROM [Sales].[Orders]							with (INDEX (	[FK_Sales_Orders_CustomerID] ))  
SELECT  * FROM [Sales].[Orders]							with (INDEX (	[FK_Sales_Orders_SalespersonPersonID] ))  
SELECT  * FROM [Sales].[Orders]							with (INDEX (	[FK_Sales_Orders_PickedByPersonID] ))  
SELECT  * FROM [Sales].[Orders]							with (INDEX (	[FK_Sales_Orders_ContactPersonID] ))  
SELECT  * FROM [Warehouse].[ColdRoomTemperatures]							with (INDEX (	[IX_Warehouse_ColdRoomTemperatures_ColdRoomSensorNumber] ))  
SELECT  * FROM [Application].[People]							with (INDEX (	[IX_Application_People_IsEmployee] ))  
SELECT  * FROM [Application].[People]							with (INDEX (	[IX_Application_People_IsSalesperson] ))  
SELECT  * FROM [Application].[People]							with (INDEX (	[IX_Application_People_FullName] ))  
SELECT  * FROM [Application].[People]							with (INDEX (	[IX_Application_People_Perf_20160301_05] ))  
SELECT  * FROM [Warehouse].[StockItems]							with (INDEX (	[FK_Warehouse_StockItems_SupplierID] ))  
SELECT  * FROM [Warehouse].[StockItems]							with (INDEX (	[FK_Warehouse_StockItems_ColorID] ))  
SELECT  * FROM [Warehouse].[StockItems]							with (INDEX (	[FK_Warehouse_StockItems_UnitPackageID] ))  
SELECT  * FROM [Warehouse].[StockItems]							with (INDEX (	[FK_Warehouse_StockItems_OuterPackageID] ))  
SELECT  * FROM [Purchasing].[PurchaseOrderLines]							with (INDEX (	[FK_Purchasing_PurchaseOrderLines_PurchaseOrderID] ))  
SELECT  * FROM [Purchasing].[PurchaseOrderLines]							with (INDEX (	[FK_Purchasing_PurchaseOrderLines_StockItemID] ))  
SELECT  * FROM [Purchasing].[PurchaseOrderLines]							with (INDEX (	[FK_Purchasing_PurchaseOrderLines_PackageTypeID] ))  
SELECT  * FROM [Purchasing].[PurchaseOrderLines]							with (INDEX (	[IX_Purchasing_PurchaseOrderLines_Perf_20160301_4] ))  
SELECT  * FROM [Purchasing].[SupplierTransactions]							with (INDEX (	[FK_Purchasing_SupplierTransactions_SupplierID] ))  
SELECT  * FROM [Purchasing].[SupplierTransactions]							with (INDEX (	[FK_Purchasing_SupplierTransactions_TransactionTypeID] ))  
SELECT  * FROM [Purchasing].[SupplierTransactions]							with (INDEX (	[FK_Purchasing_SupplierTransactions_PurchaseOrderID] ))  
SELECT  * FROM [Purchasing].[SupplierTransactions]							with (INDEX (	[FK_Purchasing_SupplierTransactions_PaymentMethodID] ))  
SELECT  * FROM [Purchasing].[SupplierTransactions]							with (INDEX (	[IX_Purchasing_SupplierTransactions_IsFinalized] ))  
SELECT  * FROM [Sales].[SpecialDeals]							with (INDEX (	[FK_Sales_SpecialDeals_StockItemID] ))  
SELECT  * FROM [Sales].[SpecialDeals]							with (INDEX (	[FK_Sales_SpecialDeals_CustomerID] ))  
SELECT  * FROM [Sales].[SpecialDeals]							with (INDEX (	[FK_Sales_SpecialDeals_BuyingGroupID] ))  
SELECT  * FROM [Sales].[SpecialDeals]							with (INDEX (	[FK_Sales_SpecialDeals_CustomerCategoryID] ))  
SELECT  * FROM [Sales].[SpecialDeals]							with (INDEX (	[FK_Sales_SpecialDeals_StockGroupID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_CustomerID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_BillToCustomerID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_OrderID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_DeliveryMethodID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_ContactPersonID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_AccountsPersonID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_SalespersonPersonID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[FK_Sales_Invoices_PackedByPersonID] ))  
SELECT  * FROM [Sales].[Invoices]							with (INDEX (	[IX_Sales_Invoices_ConfirmedDeliveryTime] ))  

